<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FREE Delivery over 499. Fulfilled by _8fa721</name>
   <tag></tag>
   <elementGuidId>ec83915b-23a4-4363-93cd-115102ccf6c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='submit'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a-autoid-0 > span.a-button-inner > input.a-button-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c3d2c43-d953-45b7-91b7-211b60bfb431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>883e2f84-af73-43cc-a2c7-060fa7aacb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asin</name>
      <type>Main</type>
      <value>B0BWXTWJ7T</value>
      <webElementGuid>2176e1b7-1ed3-4358-9ae4-c910f69854cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offerlistingid</name>
      <type>Main</type>
      <value>2%2FTZ7UGiEu%2FO%2FecSqVpaevHYbCXaM5F%2Fybt4BZU3OEZ7d+WAkBNh9eSvZuEldqzz6mQE64XcqR6oa9ob0VQ49fLX9hHk8I4wTOk%2FFHliC5vhDR+e0YeGBTCK8UksBNpU7izyIm8Ek3EzCeRw5kr31DYyK%2FW9lIZ59%2FROLV3rtbXK%2FI%2FBVhQ+kTehdxdlQ4wf</value>
      <webElementGuid>96c08c23-95a6-4700-8f44-7eaa8b63cfa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>b22c29a3-66e5-485c-973a-40e741df5b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-0-announce</value>
      <webElementGuid>29ed19f3-e5aa-4f19-8aab-c1560cc13f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-0&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>955bdb23-d894-4bcb-b132-dbd5a114e510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='submit'])[4]</value>
      <webElementGuid>05a7cf95-292d-4662-92c4-5de5ee0321c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0']/span/input</value>
      <webElementGuid>665a1043-ef9d-4129-8fdd-6b4871c62b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/div/span/span/input</value>
      <webElementGuid>66c545cf-5183-4f27-9503-f40a033d9308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>6219d4f2-b8c7-4c49-a10f-31e952c7afb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
